import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '@/components/common/Footer';
import ResponsiveNavbar from '@/components/common/ResponsiveNavbar';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mon.ne house',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ResponsiveNavbar></ResponsiveNavbar>
        {children}
          <Footer></Footer>
        </body>
    </html>
  )
}
